name: Java CI

on: 
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set Up JDK 20
        uses: actions/setup-java@v2
        with:
          java-version: 20
          distribution: 'temurin'
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.2
          arguments: build
          build-root-directory: app
      - run: make build
      - name: Publish code coverage
        uses: paambaati/codeclimate-action@v3.2.0
        env:
          CC_TEST_REPORTER_ID: ${{secrets.PROJECT73}}
          JACOCO_SOURCE_PATH: app/src/main/java
        with:
          coverageCommand: make report
          uses: cc-test-reporter after-build
          coverageLocations: ${{ github.workspace }}app//build/reports/jacoco/test/jacocoTestReport.xml:jacoco
